apiVersion: apps/v1
kind: Deployment
metadata:
  name: publisher
  namespace: ops-demo
  labels:
    app: publisher
spec:
  replicas: 2
  selector:
    matchLabels:
      app: publisher
  template:
    metadata:
      labels:
        app: publisher
    spec:
      serviceAccountName: publisher-ksa
      containers:
        - name: publisher
          image: REGION-docker.pkg.dev/PROJECT_ID/REPO/publisher:latest
          imagePullPolicy: Always
          env:
            - name: PROJECT_ID
              value: "PROJECT_ID"
            - name: TOPIC_ID
              value: "ops-topic"
            - name: SECRET_ID
              value: "APP_API_KEY"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: publisher-svc
  namespace: ops-demo
spec:
  type: LoadBalancer
  selector:
    app: publisher
  ports:
    - port: 80
      targetPort: 8080
