apiVersion: v1
kind: ServiceAccount
metadata:
  name: publisher-ksa
  namespace: ops-demo
  annotations:
    iam.gke.io/gcp-service-account: publisher-sa@PROJECT_ID.svc.id.goog
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: worker-ksa
  namespace: ops-demo
  annotations:
    iam.gke.io/gcp-service-account: worker-sa@PROJECT_ID.svc.id.goog
